version: '3.9'

services:
  api:
    image: node:16.17.0
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      NODE_ENV: dev
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
